.PHONY: clean All

All:
	@echo "----------Building project:[ Basic - Debug ]----------"
	@cd "Basic" && "$(MAKE)" -f  "Basic.mk"
clean:
	@echo "----------Cleaning project:[ Basic - Debug ]----------"
	@cd "Basic" && "$(MAKE)" -f  "Basic.mk" clean
