.PHONY: clean All

All:
	@echo "----------Building project:[ VariablesAndDataTypes - Debug ]----------"
	@cd "VariablesAndDataTypes" && "$(MAKE)" -f  "VariablesAndDataTypes.mk"
clean:
	@echo "----------Cleaning project:[ VariablesAndDataTypes - Debug ]----------"
	@cd "VariablesAndDataTypes" && "$(MAKE)" -f  "VariablesAndDataTypes.mk" clean
