.PHONY: clean All

All:
	@echo "----------Building project:[ MyName - Debug ]----------"
	@cd "MyName" && "$(MAKE)" -f  "MyName.mk"
clean:
	@echo "----------Cleaning project:[ MyName - Debug ]----------"
	@cd "MyName" && "$(MAKE)" -f  "MyName.mk" clean
